FROM debian:stable-slim
RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y hugin
RUN python3 -m pip install dropbox
RUN python3 -m pip install Flask gunicorn
WORKDIR '/hugau/'

ENV CONTEXT = 'compute'
ENV min_s = 9
ENV max_s = 255
ENV min_a = 9
ENV max_a = 255

# todo: fix insecure credentials storage
# credential is Dropbox developer project token
ARG credentials
ENV credentials = ${credentials}


COPY align_and_stitch/main.py main.py
COPY HuginAutomator.py HuginAutomator.py
COPY ConnectionHandlerDropbox.py ConnectionHandlerDropbox.py
COPY ConnectionHandler.py ConnectionHandler.py


CMD python3 main.py
