FROM debian:stable-slim
RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y hugin
RUN python3 -m pip install dropbox
RUN python3 -m pip install Flask gunicorn
WORKDIR '/hugau/'

ENV CONTEXT = compute
ENV min_s = 2
ENV max_s = 8
ENV min_a = 2
ENV max_a = 8

# todo: fix insecure credentials storage
# credential is Dropbox developer project token
ARG credentials
ENV credentials = ${credentials}

COPY align_and_stitch/main.py main.py
COPY HuginAutomator.py HuginAutomator.py
COPY ConnectionHandlerDropbox.py ConnectionHandlerDropbox.py
COPY ConnectionHandler.py ConnectionHandler.py

# Run the web service on container startup. Here we use the gunicorn
# webserver, with one worker process and 8 threads.
# For environments with multiple CPU cores, increase the number of workers
# to be equal to the cores available.
CMD exec gunicorn --bind :$PORT --workers 1 --threads 1 --timeout 0 main:app
